version: "3.9"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tasks_db
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  prisma-node-api:
    #image: docker.io/pvamshi/todo-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:pass@db:3306/tasks_db?connection_limit=5
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  mysql:
