version: "3.9"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tasks_db
    ports:
      - "3306:3306"
  prisma-node-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-server
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
# version: "3.9"
# services:
#   mysql:
#     image: mysql:latest
#     container_name: nodejs-mysql
#     hostname: localhost
#     ports:
#       - '3306:3306'
#     expose:
#       - '3306'
#     environment:
#       MYSQL_DATABASE: tasks_db
#       MYSQL_ROOT_USER: root
#       MYSQL_ROOT_PASSWORD: pass
#       MYSQL_ROOT_HOST: localhost
# 
#     volumes:
#       - mysql-data:/var/lib/mysql/data
#     restart: unless-stopped
# 
#   prisma-node-api:
#     stdin_open: true
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: todo-server
#     depends_on:
#       - mysql
#     ports:
#       - "3000:3000"
#     restart: always
# 
# volumes:
#   mysql-data:
